<?php
define('BFD_APP_VERSION','1.1.8');
define('BFD_APP_KEY','7400d8374873444ba4b2e42a27540bef');
define('BFD_APP_CHARSET','UTF-8');
define('BFD_APP_INDEX_BLOCK_ID',3);
define('BFD_APP_INDEX_BLOCK_ID_2',4);
define('BFD_APP_PIC_PATH_DIY','');//自定义附件图片前缀
define('BFD_APP_DATA_URL_PRE','http://localhost:82/');
define('BFD_APP_PIC_PATH','/data/attachment/');//
define('BFD_APP_CHARSET_HTML_DECODE','UTF-8');
define('BFD_APP_CREDITS_AWARD','2');
